image: registry.gitlab.com/pages/hugo/hugo_extended

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

test:
  script:
  - hugo
  except:
  - master

default:
  before_script:
    - apk add --update --no-cache git go
    - git submodule update --init --recursive
    - hugo mod init gitlab.com/bitsapien/blog
    - hugo mod get -u github.com/alex-shpak/hugo-book


pages:
  script:
    - hugo && gzip -k -6 $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - master
