baseURL = "https://bitsapien.gitlab.io/blog/"
languageCode = "en-us"
title = "bitsapien"
theme = "hugo-theme-basic"
enableEmoji = true 
description = "Personal site for bitsapien"

[[params.menu]] 
  name = "posts"
  url = "posts/"
[[params.menu]]
  name = "about"
  url = "about/"

[taxonomies]
  tag = "tags"
